export const testData = {
  relationship: {
    type: 'spouse',
    other: undefined,
    isEntity: undefined,
  },
  myNumber: undefined,
  locationOfDeath: {
    location: 'other',
    other: 'Home',
  },
  toursOfDuty: [
    {
      dateRange: {
        from: '2000-02-02',
        to: '2004-02-02',
      },
      serviceBranch: 'Air Force',
      rank: 'Staff Sergeant',
      serviceNumber: '123456789',
      placeOfEntry: 'Richmond, VA',
      placeOfSeparation: 'Las Vegas, NV',
    },
  ],
  veteranServedUnderAnotherName: 'false',
  previousNames: [
    {
      first: undefined,
      middle: undefined,
      last: undefined,
      suffix: undefined,
    },
  ],
  claimantEmail: 'claimantemail@test.com',
  benefitsSelection: {
    burialAllowance: true,
    plotAllowance: true,
    transportation: true,
  },
  burialAllowance: undefined,
  plotAllowance: undefined,
  transportation: undefined,
  amountIncurred: undefined,
  burialAllowanceRequested: 'nonService',
  burialCost: 0,
  previouslyReceivedAllowance: 'false',
  benefitsUnclaimedRemains: undefined,
  placeOfRemains: 'Testy Burial Sight',
  federalCemetery: 'false',
  stateCemetery: 'false',
  govtContributions: 'false',
  amountGovtContribution: 0,
  placeOfBirth: undefined,
  officialPosition: undefined,
  firmName: undefined,
  privacyAgreementAccepted: undefined,
  claimantAddress: {
    isMilitaryBaseOutside: false,
    streetAddress: '123 Test Street',
    streetAddressLine2: undefined,
    streetAddressLine3: undefined,
    city: 'Salisbury',
    country: 'USA',
    postalCode: '87987',
    state: 'AL',
  },
  claimantPhone: '999-888-7777',
  claimantFullName: {
    first: 'Tester',
    middle: 'Vicky',
    last: 'McTesty',
    suffix: 'Jr.',
  },
  veteranFullName: {
    first: 'Brody',
    middle: 'Smith',
    last: 'Tester',
    suffix: 'Sr.',
  },
  veteranSocialSecurityNumber: '987677654',
  vaFileNumber: undefined,
  burialDate: '2021-02-02',
  deathDate: '2021-01-10',
  veteranDateOfBirth: '1992-02-02',
  deathCertificate: [
    {
      name: undefined,
      size: undefined,
      confirmationCode: undefined,
    },
  ],
  transportationReceipts: [
    {
      name: undefined,
      size: undefined,
      confirmationCode: undefined,
    },
  ],
};
