export const testData = {
  relationship: {
    type: 'spouse',
    other: '',
    isEntity: null,
  },
  locationOfDeath: {
    location: 'other',
    other: 'Home',
  },
  toursOfDuty: [
    {
      dateRange: {
        from: '2000-02-02',
        to: '2004-02-02',
      },
      serviceBranch: 'Air Force',
      rank: 'Staff Sergeant',
      serviceNumber: '123456789',
      placeOfEntry: 'Richmond, VA',
      placeOfSeparation: 'Las Vegas, NV',
    },
  ],
  veteranServedUnderAnotherName: 'false',
  previousNames: [
    {
      first: '',
      middle: '',
      last: '',
      suffix: '',
    },
  ],
  claimantEmail: 'claimantemail@test.com',
  benefitsSelection: {
    burialAllowance: true,
    plotAllowance: true,
    transportation: true,
  },
  burialAllowance: null,
  plotAllowance: null,
  transportation: null,
  amountIncurred: '43.95',
  burialAllowanceRequested: 'nonService',
  burialCost: 0,
  previouslyReceivedAllowance: 'false',
  benefitsUnclaimedRemains: null,
  placeOfRemains: 'Testy Burial Sight',
  federalCemetery: 'false',
  stateCemetery: 'false',
  govtContributions: 'false',
  amountGovtContribution: 0,
  placeOfBirth: '',
  officialPosition: '',
  firmName: '',
  privacyAgreementAccepted: null,
  claimantAddress: {
    isMilitaryBaseOutside: false,
    streetAddress: '123 Test Street',
    streetAddressLine2: '',
    streetAddressLine3: '',
    city: 'Salisbury',
    country: 'USA',
    postalCode: '87987',
    state: 'AL',
  },
  claimantPhone: '999-888-7777',
  claimantFullName: {
    first: 'Tester',
    middle: 'Vicky',
    last: 'McTesty',
    suffix: 'Jr.',
  },
  veteranFullName: {
    first: 'Brody',
    middle: 'Smith',
    last: 'Tester',
    suffix: 'Sr.',
  },
  veteranSocialSecurityNumber: '987677654',
  vaFileNumber: '',
  burialDate: '2021-02-02',
  deathDate: '2021-01-10',
  veteranDateOfBirth: '1992-02-02',
  deathCertificate: [
    {
      name: '',
      size: '',
      confirmationCode: '',
    },
  ],
  transportationReceipts: [
    {
      name: '',
      size: '',
      confirmationCode: '',
    },
  ],
};
